name: le4gs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - open-clip-torch
  - cudatoolkit=11.6
  - plyfile=0.8.1
  - python 3.8.17
  - pip=22.3.1
  # - pytorch=1.12.1
  # - torchaudio=0.12.1
  # - torchvision=0.13.1

  # - pytorch==2.0.0 
  # - torchvision==0.15.1 
  # - torchaudio==2.0.1
  - colmap
  - opencv
  - tensorboard
  - jaxtyping
  - matplotlib
  - typing
  - pathlib
  - pip:
    - tqdm==4.66.1
    - torchmetrics==0.11.4
    - imagesize==1.4.1
    - kornia==0.6.12
    - omegaconf==2.3.0
    - ./simple-knn
    - ./pointops2
    - submodules/segment-anything-langsplat
    # this just breaks on my version
    # - submodules/diff-gaussian-rasterization
    # - submodules/simple-knn
    
